name: Deploy to Cloudflare

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

concurrency:
  group: deploy-cloudflare
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    # 这里从 Secrets 读取 Cloudflare API Token。
    # 请在 GitHub 项目：Settings → Secrets and variables → Actions
    # 新建一个名为 CLOUDFLARE_API_TOKEN 的 secret，值为你的 Cloudflare API Token
    # （至少需要：Account → R2:Edit 与 Workers KV/Workers Scripts 对应权限，通常可用 “Edit Cloudflare Workers” 模板+R2:Edit）
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      # 固定 wrangler 版本，避免输出差异
      - name: Install wrangler
        run: npm i -g wrangler@4.42.2

      # 幂等创建 R2 桶：使用 --json 列表并精确判断是否存在
      - name: Ensure R2 bucket exists (idempotent)
        shell: bash
        run: |
          set -euo pipefail
          # 列出桶（JSON）
          wrangler r2 bucket list --json > buckets.json
          # 精确判断 onlineclipboard-files 是否已存在
          if node -e 'const fs=require("fs");const arr=JSON.parse(fs.readFileSync("buckets.json","utf8"));process.exit(arr.some(b=>b.name==="onlineclipboard-files")?0:1)'; then
            echo "R2 bucket 'onlineclipboard-files' already exists."
          else
            echo "Creating R2 bucket 'onlineclipboard-files'..."
            wrangler r2 bucket create onlineclipboard-files
          fi

      - name: Whoami (sanity check)
        run: wrangler whoami

      - name: Deploy Worker
        run: wrangler deploy --minify

      # 仅当提供了 CLOUDFLARE_API_TOKEN 时才尝试 tail，避免无 Token 报错卡住
      - name: Tail logs (20s, optional)
        if: ${{ env.CLOUDFLARE_API_TOKEN != '' }}
        run: timeout 20s wrangler tail --format=pretty || true
