name: Deploy to Cloudflare

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm ci

      - name: Build frontend
        run: npm run build

      - name: Apply D1 migrations (remote)
        run: |
          npx wrangler d1 migrations apply web_server --remote
          if [ -f ./migrations/web_server/0002_seed.sql ]; then
            npx wrangler d1 execute web_server --remote --file=./migrations/web_server/0002_seed.sql
          fi

      - name: Ensure R2 bucket exists (first-time only)
        run: npx wrangler r2 bucket create onlineclipboard-files || echo "bucket exists"

      - name: Whoami
        run: npx wrangler whoami

      - name: Deploy Worker
        run: npx wrangler deploy --minify
