name: Deploy to Cloudflare

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

concurrency:
  group: deploy-cloudflare
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      # Cloudflare API Token（在 GitHub 项目 Settings -> Secrets -> Actions 中配置）
      CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      # 统一 wrangler 版本，避免本地与 CI 不一致导致的行为差异
      - name: Install wrangler
        run: npm i -g wrangler@4.42.2

      # 幂等创建 R2 桶：先用 JSON 列表精准判断是否存在，不存在才创建
      - name: Ensure R2 bucket exists (idempotent)
        shell: bash
        run: |
          set -euo pipefail
          # 列出所有 R2 桶（JSON）
          wrangler r2 bucket list --format=json > buckets.json
          # 用 Node 精准判断是否包含 onlineclipboard-files
          if node -e 'const fs=require("fs");const arr=JSON.parse(fs.readFileSync("buckets.json","utf8"));process.exit(arr.some(b=>b.name==="onlineclipboard-files")?0:1)'; then
            echo "R2 bucket 'onlineclipboard-files' already exists."
          else
            echo "Creating R2 bucket 'onlineclipboard-files'..."
            wrangler r2 bucket create onlineclipboard-files
          fi

      - name: Whoami (sanity check)
        run: wrangler whoami

      - name: Deploy Worker
        run: wrangler deploy --minify

      - name: Tail logs (20s, optional)
        if: ${{ always() }}
        run: timeout 20s wrangler tail --format=pretty || true
